# travis config

language: r

r_github_packages:
  - jimhester/covr
  - jakobbossek/smoof

after_success:
  - Rscript -e 'library(covr);coveralls(exclusions = c("src/avl.c", "src/r_ind.c", "src/hv.c"))'

notifications:
  email:
    recipients:
      - bossek@wi.uni-muenster.de
      - surmann@statistik.tu-dortmund.de
    on_success: change
    on_failure: always
